# MODULE NAME: ErrorLog.py
# Description of MODULE:
# ErrorLog.py contains the functions required to create logfiles containing OSError, WindowsError, AttributeError and
# IndexError entries in the default running directory of ShadowEC. The logfiles are used for debugging, logging and
# documentation purposes.
# ------------------------------------------------------------------------------------------------------------------
# Author: Kenneth Damlien
# Email: kennethdamlien@live.no
# ------------------------------------------------------------------------------------------------------------------
# IMPORTS GOES HERE:
import os
# ------------------------------------------------------------------------------------------------------------------
# GLOBAL VARIABLES GOES HERE:
directory = "ErrorLogs"
# ------------------------------------------------------------------------------------------------------------------
# FUNCTIONS GOES HERE:

def createlogfile(filename):
    # Create Log File based on given filename, filename is based on source of error (function or module name)
    with open(directory + "\\" + filename, "a") as f:
        f.write("This log file details the errors encountered during execution of ShadowEC")

def printtofile(filename, error, errortype):
    # Append each error generated by a function on a new line on the created file.
    # TODO: TIMESTAMP OF ERROR
    with open(directory + "\\" + filename, "a") as f:
        f.write(errortype + ": " + error + "\n")

def error(error, filename, errortype):
    error = str(error)
    try:
        # Create folder "ErrorLogs" in root ShadowEC directory
        os.makedirs(directory)
        # Create File in folder "ErrorLogs"

    except OSError as e:
        pass
    # Append each error to file
    printtofile(filename, error, errortype)